import BlogSlider from '@/components/BlogSlider';
import ClientsFeedbackSlider from '@/components/ClientsFeedbackSlider';
import GetInTouch from '@/components/GetInTouch';
import helper from '@/libs/helper';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Obchodné podmienky – LeonLogic digitálna agentúra',
    description: 'Prečítajte si obchodné podmienky spoločnosti LeonLogic. Podmienky používania webu, právne informácie, ochrana údajov a povinnosti klientov.',
    openGraph: {
        ...helper.openGraphData,
        title: 'Obchodné podmienky – LeonLogic digitálna agentúra',
        description: 'Prečítajte si obchodné podmienky spoločnosti LeonLogic. Podmienky používania webu, právne informácie, ochrana údajov a povinnosti klientov.',
        url: process.env.NEXT_PUBLIC_APP_URL + '/terms-and-conditions',
        type: 'article',
    },
    twitter: {
        ...helper.twitterData,
        title: 'Obchodné podmienky – LeonLogic digitálna agentúra',
        description: 'Prečítajte si obchodné podmienky spoločnosti LeonLogic. Podmienky používania webu, právne informácie, ochrana údajov a povinnosti klientov.',
    },
    alternates: {
        canonical: `${process.env.NEXT_PUBLIC_APP_URL}/terms-and-conditions`,
        languages: { 'x-default': `${process.env.NEXT_PUBLIC_APP_URL}/terms-and-conditions` },
    },
};
const page = () => {
    return (
        <>
            <section className="pb-12 pt-32 md:pt-52">
                <div className="container">
                    <div>
                        <h1 className="text-[28px] font-bold leading-8">Terms and Conditions</h1>
                        <p className="text-gray dark:text-[#9199B5] mt-5 md:mt-8">
                            This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the
                            amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This
                            electronic record is generated by a computer system and does not require any physical or digital signatures.
                        </p>
                        <p className="text-gray dark:text-[#9199B5] mt-5">
                            his document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines)
                            Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of
                            careers.padme.com, life. padme.com & blog.padme.com website.
                        </p>
                        <p className="text-gray dark:text-[#9199B5] mt-5">
                            This Website, including all Materials present (excluding any applicable third party materials), is the property of Myntra and is
                            copyrighted and protected by worldwide copyright laws and treaty provisions. You hereby agree to comply with all copyright laws
                            worldwide in Your use of this Website and to prevent any unauthorized copying of the Materials.
                        </p>
                        <p className="text-gray dark:text-[#9199B5] mt-5">
                            By accessing this website we assume you accept these terms and conditions. Do not continue to use Website Name if you do not agree
                            to take all of the terms and conditions stated on this page.
                        </p>
                        <p className="text-gray dark:text-[#9199B5] mt-5">{`The following terminology applies to these Terms
                            and Conditions,
                            Privacy Statement and
                            Disclaimer Notice and all
                            Agreements:
                            “Client”, “You” and “Your” refers to you, the person log on this website and compliant to
                            the Company's
                            terms and conditions. “The Company”, “Ourselves”, “We”, “Our” and “Us”, refers to our
                            Company. “Party”, “Parties”, or
                            “Us”, refers to both the Client and
                            ourselves.`}</p>
                        <h2 className="text-[28px] font-bold leading-8 mt-12 md:mt-16">Cookies</h2>
                        <p className="text-gray dark:text-[#9199B5] mt-5 md:mt-8">{`We employ the use of cookies. By accessing
                            Website Name, you
                            agreed to
                            use cookies in
                            agreement with the Company
                            Name's
                            Privacy Policy.`}</p>
                        <p className="text-gray dark:text-[#9199B5] mt-2.5">{`Most interactive websites use cookies to let us
                            retrieve the user's
                            details for each visit.
                            Cookies are used by our website to
                            enable
                            the functionality of certain areas to make it easier for people visiting our website. Some
                            of our affiliate/advertising
                            partners may
                            also use cookies.`}</p>
                        <h2 className="text-[28px] font-bold leading-8 mt-12 md:mt-16">License</h2>
                        <p className="text-gray dark:text-[#9199B5] mt-5 md:mt-8">
                            Unless otherwise stated, Company Name and/or its licensors own the intellectual property rights for all material on Website Name.
                            All intellectual property rights are reserved. You may access this from Website Name for your own personal use subjected to
                            restrictions set in these terms and conditions.
                        </p>
                        <ul className="list-disc mt-12 md:mt-16 text-gray dark:text-[#9199B5] space-y-2 list-inside">
                            <li>Republish material from Website Name</li>
                            <li>Sell, rent or sub-license material from Website Name</li>
                            <li>Reproduce, duplicate or copy material from Website Name</li>
                            <li>Redistribute content from Website Name</li>
                        </ul>
                        <p className="text-gray dark:text-[#9199B5] mt-2.5">
                            Parts of this website offer an opportunity for users to post and exchange opinions and information in certain areas of the website.
                            Company Name does not filter, edit, publish or review Comments prior to their presence on the website. Comments do not reflect the
                            views and opinions of Company Name,its agents and/or affiliates. Comments reflect the views and opinions of the person who post
                            their vie
                        </p>
                        <p className="text-gray dark:text-[#9199B5] mt-2.5">
                            Company Name reserves the right to monitor all Comments and to remove any Comments which can be considered inappropriate, offensive
                            or causes breach of these Terms and Conditions.
                        </p>
                        <h2 className="font-semibold mt-12 md:mt-16">You warrant and represent that:</h2>
                        <ul className="list-disc list-inside mt-2.5 text-gray dark:text-[#9199B5] space-y-2">
                            <li>You are entitled to post the Comments on our website and have all necessary licenses and consents to do so;</li>
                            <li>
                                The Comments do not invade any intellectual property right, including without limitation copyright, patent or trademark of any
                            </li>
                        </ul>
                        <h2 className="font-semibold mt-5">Third party;</h2>
                        <ul className="list-disc list-inside mt-2.5 text-gray dark:text-[#9199B5] space-y-2">
                            <li>
                                {' '}
                                Third party; The Comments do not contain any defamatory, libelous, offensive, indecent or otherwise unlawful material which is
                                an invasion of privacy
                            </li>
                        </ul>
                        <p className="text-gray dark:text-[#9199B5] mt-5">
                            You hereby grant Company Name a non-exclusive license to use, reproduce, edit and authorize others to use, reproduce and edit any of
                            your Comments in any and all forms, formats or media.
                        </p>
                        <h2 className="text-[28px] font-bold leading-8 mt-12 md:mt-16">Hyperlinking to our Content</h2>
                        <p className="text-gray dark:text-[#9199B5] mt-8">
                            The following organizations may link to our Website without prior written approval:
                        </p>
                        <ul className="list-disc list-inside mt-2.5 text-gray dark:text-[#9199B5] space-y-2">
                            <li>Government agencies;</li>
                            <li>earch engines;</li>
                            <li>News organizations;</li>
                            <li>
                                Online directory distributors may link to our Website in the same manner as they hyperlink to the Websites of other listed
                                businesses; and System wide Accredited Businesses except soliciting non-profit organizations, charity shopping malls, and
                                charity fundraising groups{' '}
                            </li>
                        </ul>
                    </div>
                </div>
            </section>

            <section className="py-12 md:py-16">
                <BlogSlider />
            </section>

            <section className="py-10 md:py-16">
                <ClientsFeedbackSlider />
            </section>

            <section className="bg-[url('/assets/images/newsletter.png')] bg-cover bg-bottom bg-no-repeat bg-success py-12 relative">
                <GetInTouch />
            </section>
        </>
    );
};

export default page;
